import Footer from "./components/shared/footer/Footer";
import Header from "./components/shared/header/Header";
import "./globals.scss";
import "./base.scss";
import "./typography.scss";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="main">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
